alias: EcoFlow - Сповіщення про стан батареї
description: Сповіщення про низький/критичний заряд, перегрів та повний заряд батареї
triggers:
  # Низький заряд батареї (<20%)
  - platform: numeric_state
    entity_id: sensor.ecoflow_delta_pro_3_system_battery_level
    below: 20
    for:
      minutes: 1
    id: low_battery
  # Критичний заряд батареї (<10%)
  - platform: numeric_state
    entity_id: sensor.ecoflow_delta_pro_3_system_battery_level
    below: 10
    for:
      minutes: 1
    id: critical_battery
  # Висока температура (>40°C)
  - platform: numeric_state
    entity_id: sensor.ecoflow_delta_pro_3_max_cell_temperature
    above: 40
    for:
      minutes: 5
    id: high_temp
  # Батарея заряджена (100%)
  - platform: state
    entity_id: binary_sensor.ecoflow_delta_pro_3_battery_full
    to: "on"
    for:
      minutes: 2
    id: battery_full
conditions:
  # Для низького/критичного заряду - перевіряємо що є споживання
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.id in ['high_temp', 'battery_full'] }}"
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger.id in ['low_battery', 'critical_battery'] }}"
          - condition: numeric_state
            entity_id: sensor.ecoflow_delta_pro_3_total_output_power
            above: 0
  # Для повного заряду - перевіряємо що зарядка активна
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.id != 'battery_full' }}"
      - condition: state
        entity_id: binary_sensor.ecoflow_delta_pro_3_charging
        state: "on"
actions:
  - variables:
      # Визначаємо тип сповіщення
      alert_type: "{{ trigger.id }}"
      
      # Загальні параметри
      battery_level: "{{ states('sensor.ecoflow_delta_pro_3_system_battery_level') | round(0) }}"
      battery_health: "{{ states('sensor.ecoflow_delta_pro_3_battery_health') | round(0) }}"
      battery_temp: "{{ states('sensor.ecoflow_delta_pro_3_max_cell_temperature') | round(1) }}"
      discharge_remaining_time: "{{ states('sensor.ecoflow_delta_pro_3_system_discharge_remaining_time') }}"
      charge_remaining_time: "{{ states('sensor.ecoflow_delta_pro_3_system_charge_remaining_time') }}"
      output_power: "{{ states('sensor.ecoflow_delta_pro_3_total_output_power') | round(0) }}"
      cycles: "{{ states('sensor.ecoflow_delta_pro_3_cycles') }}"
      is_charging: "{{ is_state('binary_sensor.ecoflow_delta_pro_3_charging', 'on') }}"
      charge_power: "{{ states('number.ecoflow_delta_pro_3_ac_charging_power') }}"
      
      # Заголовок та повідомлення залежно від типу сповіщення
      notification_title: |
        {% if alert_type == 'low_battery' %}
          ⚠️ Низький заряд EcoFlow
        {% elif alert_type == 'critical_battery' %}
          🚨 КРИТИЧНИЙ заряд EcoFlow!
        {% elif alert_type == 'high_temp' %}
          🌡️ EcoFlow перегрівається!
        {% elif alert_type == 'battery_full' %}
          ✅ EcoFlow повністю заряджений
        {% endif %}
      
      notification_message: |
        {% if alert_type == 'low_battery' %}
          🔋 {{ battery_level }}%
          ⏱️ {{ discharge_remaining_time }}
          ⚡ {{ output_power }}W
        {% elif alert_type == 'critical_battery' %}
          🔋 {{ battery_level }}%!
          ⏱️ {{ discharge_remaining_time }}
          ⚡ {{ output_power }}W
          ⚠️ ТЕРМІНОВО ЗАРЯДЖАННЯ!
        {% elif alert_type == 'high_temp' %}
          🌡️ {{ battery_temp }}°C
          ⚠️ Перевірте вентиляцію!
          🔋 {{ battery_level }}%
          ⚡ {{ output_power }}W
          {% if is_charging %}
          🔌 {{ charge_power }}W
          {% endif %}
        {% elif alert_type == 'battery_full' %}
          🔋 {{ battery_level }}%
          ✅ Можна вимикати заряджання
          📊 {{ battery_health }}%
          🔄 {{ cycles }}
        {% endif %}
  
  - action: notify.notify
    data:
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
    enabled: true

mode: single

