alias: EcoFlow - Перемикання джерела живлення
description: Сповіщення при перемиканні між міською мережею та батареєю
triggers:
  # Перемикання на мережу
  - platform: state
    entity_id: binary_sensor.ecoflow_delta_pro_3_ac_input_connected
    to: "on"
    for:
      seconds: 10
    id: switch_to_grid
  # Перемикання на батарею
  - platform: state
    entity_id: binary_sensor.ecoflow_delta_pro_3_ac_input_connected
    to: "off"
    for:
      seconds: 10
    id: switch_to_battery
conditions:
  # Для перемикання на батарею - перевіряємо що розрядка активна
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.id == 'switch_to_grid' }}"
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger.id == 'switch_to_battery' }}"
          - condition: state
            entity_id: binary_sensor.ecoflow_delta_pro_3_discharging
            state: "on"
actions:
  - variables:
      # Визначаємо режим роботи
      is_grid_mode: "{{ trigger.id == 'switch_to_grid' }}"
      
      # Загальні параметри
      battery_level: "{{ states('sensor.ecoflow_delta_pro_3_system_battery_level') | round(0) }}"
      battery_temp: "{{ states('sensor.ecoflow_delta_pro_3_max_cell_temperature') | round(1) }}"
      
      # Для режиму мережі
      charge_power: "{{ states('sensor.ecoflow_delta_pro_3_ac_input_power') | round(0) }}"
      charge_remaining_time: "{{ states('sensor.ecoflow_delta_pro_3_system_charge_remaining_time') }}"
      
      # Для режиму батареї
      output_power: "{{ states('sensor.ecoflow_delta_pro_3_total_output_power') | round(0) }}"
      discharge_remaining_time: "{{ states('sensor.ecoflow_delta_pro_3_system_discharge_remaining_time') }}"
      
      # Заголовок та повідомлення
      notification_title: |
        {% if is_grid_mode %}
          🏠 Живлення від мережі
        {% else %}
          🔋 Живлення від EcoFlow
        {% endif %}
      
      notification_message: |
        {% if is_grid_mode %}
          ⚡ {{ charge_power }}W
          ⏱️ {{ charge_remaining_time }}
          🔋 {{ battery_level }}%
        {% else %}
          ⚡ {{ output_power }}W
          ⏱️ {{ discharge_remaining_time }}
          🔋 {{ battery_level }}%
        {% endif %}
  
  - action: notify.notify
    data:
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
    enabled: true

mode: single

